"""Add uniqueconstraint for user_id-name

Revision ID: 6325a0d21651
Revises: 715be686c3ef
Create Date: 2025-02-07 19:22:58.222046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6325a0d21651"
down_revision: Union[str, None] = "715be686c3ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_user_habit", "habits", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_habit", "habits", type_="unique")
    # ### end Alembic commands ###
