"""Add uniqueconstraint date-habit

Revision ID: 7bbac31cc8c7
Revises: 17bbeaf8fad0
Create Date: 2025-02-09 10:13:02.201982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bbac31cc8c7"
down_revision: Union[str, None] = "17bbeaf8fad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("habit_trackings_date_key", "habit_trackings", type_="unique")
    op.create_unique_constraint(
        "unique_habit_tracking_date", "habit_trackings", ["habit_id", "date"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_habit_tracking_date", "habit_trackings", type_="unique")
    op.create_unique_constraint("habit_trackings_date_key", "habit_trackings", ["date"])
    # ### end Alembic commands ###
