"""Add table kafka_messages

Revision ID: f4424ee7d3b7
Revises: 7bbac31cc8c7
Create Date: 2025-02-17 18:11:58.113325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4424ee7d3b7"
down_revision: Union[str, None] = "7bbac31cc8c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kafka_messages",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint(
            "telegram_id", "date", name="unique_telegram_id_date_message"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kafka_messages")
    # ### end Alembic commands ###
