services:
#  server:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      command: ["uvicorn api.main:app --host 0.0.0.0 --port 5000 --reload"]
#      ports:
#        - "5000:5000"
#      restart: always
#      env_file:
#        - .env
#      environment:
#        - DATABASE_URL=postgresql+asyncpg://${DB__USER}:${DB__PASSWORD}@${DB__HOST}:${DB__PORT}/${DB__NAME}
#      depends_on:
#        postgres:
#          condition: service_healthy
#      networks:
#        - app-network

  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=${DB__NAME}
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - log_destination=stderr
      - logging_collector=on
      - log_directory=/var/lib/postgresql/data/log
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB__NAME} -U ${DB__USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "${DB__PORT}:${DB__PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
