"""Add telegram_id in table users

Revision ID: 715be686c3ef
Revises: 1502cff64f53
Create Date: 2025-02-06 14:25:15.248577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "715be686c3ef"
down_revision: Union[str, None] = "1502cff64f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
