from starlette.status import HTTP_404_NOT_FOUND

from exceptions.responses import user_with_telegram_id_not_found_response

auth_telegram_responses = {HTTP_404_NOT_FOUND: user_with_telegram_id_not_found_response}
